Repository 4-design/for-ui, pull requests merged in 2022-05, with the labels that each got.

#599 feat: Support react v18
  src/modal/ModalContent/index.tsx
  src/table/TableScroller.tsx
Labels: feat

#600 fix: release-drafter github actions
  .github/workflows/publish.yml
Labels: fix

#609 chore: ブランドタイトルを3design-uiに差し替え
  .storybook/addons.js
  .storybook/manager.js
Labels: chore

#614 feat: yarn v3を使うように変更
  .github/workflows/lint.yml
  .gitignore
  .yarn/releases/yarn-3.0.0.cjs
  .yarnrc.yml
  package.json
  src/table/Table.tsx
  yarn.lock
Labels: feat

#610 refactor: Chipコンポーネントのデザイン調整
  src/chip/Chip.stories.tsx
  src/chip/Chip.tsx
  src/styles/tailwind.v2.css
  tailwind.config.js
Labels: refactor
