Repository 4-design/for-ui, pull requests merged in 2022-08, with the labels that each got.

#666 feat: React-Tableのソート機能の実装
  src/table/Table.stories.tsx
  src/table/Table.tsx
Labels: feat

#692 release: v2.1.5
  package.json
Labels: release

#693 release: v2.1.6
  package.json
Labels: release

#695 feat: vite 導入
  .github/pull_request_template.md
  .storybook/main.cjs
  .storybook/preview.jsx
  package.json
  src/checkbox/Checkbox.stories.tsx
  src/modal/Modal.stories.tsx
  src/typography/Typography.stories.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feat

#696 feat: Badge 対応
  package.json
  src/badge/Badge.stories.tsx
  src/badge/Badge.tsx
Labels: feat

#698 feat: eslint-plugin-tailwindcss / prettier-plugin-tailwindcss 導入
  .eslintrc.js
  .prettierignore
  package.json
  prettier.config.js
  src/card/Card.tsx
  src/divider/Divider.stories.tsx
  src/layout/Header.tsx
  src/loader/Loader.stories.tsx
  src/loader/Loader.tsx
  src/modal/Modal.tsx
  src/modal/ModalFooter/index.tsx
  src/modal/ModalHeader/index.tsx
  src/radio/Radio.stories.tsx
  src/radio/RadioGroup.tsx
  src/skeleton/Skeleton.stories.tsx
  src/stepper/Stepper.stories.tsx
  src/tab/Tabs.stories.tsx
  src/table/Table.tsx
  src/table/TableCell.tsx
  src/table/TablePagination.tsx
  src/tag/Tag.stories.tsx
  yarn.lock
Labels: feat

#699 feat: Tag実装
  src/tag/Tag.stories.tsx
  src/tag/Tag.tsx
Labels: feat

#700 feat: Divider実装
  src/divider/Divider.tsx
Labels: feat

#697 feat: Button 実装
  .github/workflows/lint.yml
  package.json
  src/button/Button.stories.tsx
  src/button/Button.tsx
  src/button/index.tsx
  yarn.lock
Labels: feat

#702 fix: npm publish 周りのバグ修正
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: fix

#703 fix: release label自動付与
  .github/release-drafter.yml
Labels: fix

#704 release: 2.1.7
  package.json
Labels: release

#705 chore: リリース作成 アクションを削除
  .github/workflows/release.yml
Labels: chore

#706 feat: Switch 実装
  src/switch/Switch.stories.tsx
  src/switch/Switch.tsx
  src/switch/SwitchGroup.tsx
Labels: feat

#710 fix: Storybook アップグレード
  .storybook/main.cjs
  package.json
  yarn.lock
Labels: fix

#711 feat: Menu 実装
  .storybook/preview.tsx
  src/menu/Menu.stories.tsx
  src/menu/Menu.tsx
  src/menu/MenuItem.tsx
  tailwind.config.js
Labels: feat

#712 feat: Typography 実装
  .storybook/preview.tsx
  src/typography/Typography.stories.tsx
  src/typography/Typography.tsx
Labels: feat

#713 feat: Loader 廃止
  src/index.ts
  src/loader/Loader.stories.tsx
  src/loader/Loader.tsx
  src/loader/index.tsx
Labels: feat

#707 feat: Chip実装
  src/chip/Chip.stories.tsx
  src/chip/Chip.tsx
  src/chip/index.tsx
  src/index.ts
  tailwind.config.js
Labels: feat

#708 feat: Checkbox実装
  src/checkbox/Checkbox.stories.tsx
  src/checkbox/Checkbox.tsx
Labels: feat

#718 feat: Spacer storybook復活
  src/spacer/Spacer.stories.tsx
Labels: feat

#720 fix: srcディレクトリにstylesをいれないようにする
  .storybook/preview.tsx
  styles/global.css
  styles/tailwind.v1.css
  styles/tailwind.v2.css
Labels: fix

#714 feat: Tab 実装
  src/tab/Tab.tsx
  src/tab/TabList.tsx
  src/tab/TabPanel.tsx
  src/tab/Tabs.stories.tsx
  src/tab/Tabs.tsx
Labels: feat

#715 feat: Modal 実装
  .storybook/preview.tsx
  src/button/Button.tsx
  src/modal/Modal.stories.tsx
  src/modal/Modal.tsx
  src/modal/ModalContent.tsx
  src/modal/ModalFooter.tsx
  src/modal/ModalHeader.tsx
  tailwind.config.js
Labels: feat

#719 feat: Vite ライブラリー配布設定
  package.json
  vite.config.ts
  yarn.lock
Labels: feat

#724 feat: Dropzone 実装
  src/dropzone/Dropzone.stories.tsx
  src/dropzone/Dropzone.tsx
Labels: feat

#716 feat: Radio実装
  src/radio/Radio.tsx
  src/radio/RadioGroup.tsx
Labels: feat

#722 feat: TextField 実装
  src/textField/TextField.stories.tsx
  src/textField/TextField.tsx
Labels: feat

#725 chore: dependencies
  package.json
  renovate.json
  rollup.config.js
  yarn.lock
Labels: dependencies

#729 fix: icon property バグ修正 / font-size remを使用 > tailwindcss.config.js
  tailwind.config.js
Labels: fix

#730 fix: package.jsonのtypes 先の間違いを修正
  package.json
Labels: fix

#726 feat: Select 実装
  src/dropzone/index.tsx
  src/index.ts
  src/menu/MenuItem.tsx
  src/select/Select.stories.tsx
  src/select/Select.tsx
  src/select/index.tsx
  src/textField/TextField.tsx
  src/textField/index.tsx
Labels: feat

#723 feat: Table 実装
  .eslintignore
  src/table/Table.stories.tsx
  src/table/Table.tsx
  src/table/TableCell.tsx
  src/table/TablePagination.tsx
  src/table/TableScroller.tsx
  styles/global.css
  tailwind.config.js
Labels: feat

#731 release: v3.0.0
  package.json
Labels: release

#734 feat: Drawer実装
  .storybook/manager.js
  src/drawer/Drawer.stories.tsx
  src/drawer/Drawer.tsx
  src/drawer/index.tsx
  src/index.ts
Labels: feat

#737 release: v3.1.0
  package.json
Labels: release

#709 feat: Tableコンポーネントでソート機能設定時にStyleを渡るようにする
  src/table/Table.stories.tsx
  src/table/Table.tsx
Labels: feat
